// main.rs

use sycamore::prelude::*;

use frontend_lib::components::header::Header;
use frontend_lib::components::footer::Footer;

fn main() {
    sycamore::render(|cx| view! { cx,
        Header {}
        main {
            article {
                h2 { "2022-10-01" }
                h3 { "Site Started" }
                p { "Site initially created."}
            }
            article {
                h2 { "2022-10-02" }
                h3 { "Re-factor to include Rocket" }
                p { "Re-factored and broke code into a front end and server. Rocket serves the files generated by Trunk/Sycamore."}
            }
        }
        Footer {}
    });
}
