// data.rs

pub fn get_articles() -> Vec<&'static str> {
    let content_articles = vec![
        "2022-10-01: Site initially crated",
        "2022-10-02: Re-factored and broke code into a front end and server. Rocket serves the files generated by Trunk/Sycamore.",
        "2022-10-03: Today I learned how to use routes in Sycamore to enable navigation between pages.",
        "2022-10-04: Re-factored to create a data file containing a function that returns a vector of static strings. The static strings are rendered out as a view."
    ];
    content_articles
}
